## normalize

In [1]:
import numpy as np

In [11]:
x = np.array(np.random.randn(3,4))

In [12]:
x

array([[-1.10340393,  1.94520336,  1.89504358,  0.01188574],
       [ 1.18200526,  0.89026585,  0.37347098,  0.89632574],
       [-0.20727722,  0.40831634, -1.34979255, -0.64089146]])

In [13]:
x.shape

(3, 4)

In [16]:
x > np.min(x)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]], dtype=bool)

In [17]:
x < np.max(x)

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

## one-hot

In [22]:
import numpy as np
from sklearn import preprocessing

# Example labels
labels = np.array([1,5,3,2,1,4,2,1,3, 0])

# Create the encoder
lb = preprocessing.LabelBinarizer()

# Here the encoder finds the classes and assigns one-hot vectors 
lb.fit(labels)

# And finally, transform the labels into one-hot encoded vectors
one_hot = lb.transform(labels)

In [23]:
one_hot

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [24]:
targets = np.array([[2, 3, 4, 0]])

In [25]:
targets

array([[2, 3, 4, 0]])

In [26]:
targets.reshape(-1)

array([2, 3, 4, 0])

In [27]:
x

array([[-1.10340393,  1.94520336,  1.89504358,  0.01188574],
       [ 1.18200526,  0.89026585,  0.37347098,  0.89632574],
       [-0.20727722,  0.40831634, -1.34979255, -0.64089146]])

In [34]:
eye = np.eye(5)
eye

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [35]:
eye[nb]

array([[ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [36]:
xt = np.array([[1,2,3],[4,5,6],[7,8,9]])
xt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
nb =  np.array([1,2,0,0,2,1])
nb

array([1, 2, 0, 0, 2, 1])

In [37]:
xt[nb]

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [38]:
xt[[1,2,0]]

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [46]:
aList = [None]
bList = [2009, 'manni']
aList.extend(bList)

In [47]:
aList

[None, 2009, 'manni']

In [50]:
xx = list([None]).extend(bList)

In [52]:
aList

[None, 2009, 'manni']

In [55]:
(aList,)

([None, 2009, 'manni'],)

In [57]:
my_list = [1,2,3,4,5,6]

In [61]:
np.prod(my_list)

720

In [62]:
def one_hot_encode(x):
    """
    One hot encode a list of sample labels. Return a one-hot encoded vector for each label.
    : x: List of sample Labels
    : return: Numpy array of one-hot encoded labels
    """
    # TODO: Implement Function
    nb_classes = 10
    targets = np.array(x).reshape(-1)
    one_hot_targets = np.eye(nb_classes)[targets]   
    return one_hot_targets

In [64]:
xin = [1,2,3,0,9]

In [65]:
one_hot_encode(xin)

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])