In [1]:
import numpy as np

In [2]:
sigma = np.array([1,2,3,4]).reshape(1,4)
sigma

array([[1, 2, 3, 4]])

In [3]:
a =  np.array([2,4,8]).reshape(1,3)
a

array([[2, 4, 8]])

In [4]:
sigma * a.T

array([[ 2,  4,  6,  8],
       [ 4,  8, 12, 16],
       [ 8, 16, 24, 32]])

In [5]:
a.T.dot(sigma)

array([[ 2,  4,  6,  8],
       [ 4,  8, 12, 16],
       [ 8, 16, 24, 32]])

In [7]:
ab = np.array([[1,2,3],[4,5,6]])

In [8]:
ab

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
ab[0] -= [3,2,1]

In [11]:
ab

array([[-2,  0,  2],
       [ 4,  5,  6]])

In [12]:
a.shape

(1, 3)

In [13]:
abb = list(a)

In [14]:
abb

[array([2, 4, 8])]

In [15]:
a.reshape(None,)

array([[2, 4, 8]])

In [16]:
a.shape

(1, 3)

In [17]:
a.reshape(None)

array([[2, 4, 8]])

In [18]:
ac = np.squeeze(a)

In [19]:
ac

array([2, 4, 8])

In [20]:
ac.shape

(3,)

In [21]:
l1 = list()

In [22]:
l1

[]

In [23]:
l2 = []

In [24]:
l2

[]

In [25]:
s1 = set()

In [26]:
s1

set()

In [36]:
type(s1)

set

In [27]:
s2 = ()

In [28]:
s2

()

In [35]:
s2.add(2)

AttributeError: 'tuple' object has no attribute 'add'

In [29]:
type(s2)

tuple

In [30]:
s3 = (1,)

In [31]:
s3

(1,)

In [32]:
type(s3)

tuple

In [33]:
s4 = (1)

In [34]:
s4

1

In [37]:
tp1 = (1,2,3,4)

In [38]:
tp1[1]

2

In [39]:
abs(-1)

1

In [40]:
np.abs(-1)

1

In [41]:
ls1 = [1,2,3,4
    ]

In [42]:
len(ls1)

4

In [55]:
x = [6, 14, 3]
w = [0.5, 0.25, 1.4]

In [56]:
x * w

TypeError: can't multiply sequence by non-int of type 'list'

In [57]:
x+w

[6, 14, 3, 0.5, 0.25, 1.4]

In [58]:
x - w

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [59]:
relt = 0
for x1, x2 in zip(x, w):
    relt += x1 * x2
relt

10.7

In [60]:
x = np.array([6, 14, 3])
w = np.array([0.5, 0.25, 1.4])

In [61]:
sum(x * w)

10.699999999999999

In [62]:
np.matmul(x, w)

10.699999999999999

In [63]:
w1  = np.array([[1, 2], [3, 4]])

In [64]:
w1.shape

(2, 2)

In [73]:
w2 = w1.reshape(-1)
w2

array([1, 2, 3, 4])

In [68]:
w1

array([[1, 2],
       [3, 4]])

In [70]:
w2.shape

(4,)

In [72]:
w3 = np.reshape(w1, -1)
w3

array([1, 2, 3, 4])

In [74]:
w3.shape

(4,)

In [78]:
x1d = np.array([1,2,3])
x1d

array([1, 2, 3])

In [79]:
x2d = np.array([[1],[2],[3]])
x2d

array([[1],
       [2],
       [3]])

In [80]:
x1d.shape

(3,)

In [81]:
x2d.shape

(3, 1)

In [82]:
x1d - x2d

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [83]:
x2d - x1d

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [85]:
x2dd = x2d *2
x2dd

array([[2],
       [4],
       [6]])

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [87]:
x2d.shape[0]

3

In [88]:
len(x2d)

3

In [93]:
grad_cost = np.array([[1,2,3],[3,4,5]])
grad_cost

array([[1, 2, 3],
       [3, 4, 5]])

In [96]:
np.sum(grad_cost, axis=0, keepdims=False)

array([4, 6, 8])