In [6]:
list1 = list()

In [3]:
list1[0][0] = 1

IndexError: list index out of range

In [7]:
list1[0] = [0,1]

IndexError: list assignment index out of range

> one space --> two spaces --> three spaces

In [14]:
list2 = 'ab cd  eg   h'

In [16]:
type(list2)

str

In [17]:
ls2_split1 = list2.split()
ls2_split1

['ab', 'cd', 'eg', 'h']

In [18]:
ls2_split2 = list2.split(' ')
ls2_split2

['ab', 'cd', '', 'eg', '', '', 'h']

In [1]:
import numpy as np

In [23]:
np1 = np.array([[1,2,3],[5,6,7]])

In [28]:
np1.shape[0]

2

In [29]:
int(11.1)

11

In [30]:
np.floor(11.1)

11.0

In [31]:
np.int(11.2)

11

In [33]:
np2 = np.array([[[1],[2]],
                            [[3],[4]],
                            [[5],[6]]])
np2

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [38]:
np2.shape

(3, 2, 1)

In [35]:
np2[:,-1, :]

array([[2],
       [4],
       [6]])

In [36]:
np2[:,-1]

array([[2],
       [4],
       [6]])

In [37]:
np2[:,-1].shape

(3, 1)

In [3]:
a0 = np.array([1,2,3,4,5,6])
a1 = np.array([1,2,3,4,5,6])

In [5]:
a0[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
import tensorflow as tf

In [30]:
n = 5
k = 10

> 1D lookup

In [31]:
embedding = tf.Variable(tf.random_uniform((n, k), -1, 1))
embed1d = tf.nn.embedding_lookup(embedding, [0, 1, 2]) # 3

In [32]:
embed1d.shape

TensorShape([Dimension(3), Dimension(10)])

> 2D lookup

In [33]:
embed2d = tf.nn.embedding_lookup(embedding, [[0,1], [3, 4], [5, 6]])  # 3x2 ---> 3x2x10

In [34]:
embed2d.shape

TensorShape([Dimension(3), Dimension(2), Dimension(10)])

> 3D lookup

In [36]:
embed3d = tf.nn.embedding_lookup(embedding, id3) # 3x2x3--> 3x2x3x10

In [37]:
embed3d.shape

TensorShape([Dimension(3), Dimension(2), Dimension(3), Dimension(10)])

In [49]:
id3 = [
            [[1,2, 3], [3, 4, 5]],
             [[1,2, 3], [3, 4, 5]],
              [[1,2, 3], [3, 4, 5]]
        ]

In [50]:
array3 = np.array( [
            [[1,2, 3], [3, 4, 5]],
             [[1,2, 3], [3, 4, 5]],
              [[1,2, 3], [3, 4, 5]]
        ])

In [51]:
array3.shape

(3, 2, 3)

In [52]:
len(array3)    # the first dimension

3

In [53]:
array3.ndim  # the dimension number of array

3

In [54]:
array3.size  # the total number of element in array

18

In [55]:
len(id3)

3

In [58]:
(array3[:2]).shape

(2, 2, 3)

## generator in enumerate

In [66]:
def get_row(n_step):
    for ii in range(n_step):
        yield list(range(ii+1))

In [67]:
g = get_row(10)

In [68]:
next(g)

[0]

In [69]:
next(g)

[0, 1]

In [70]:
next(g)

[0, 1, 2]

In [71]:
next(g)

[0, 1, 2, 3]

In [79]:
for i, r in enumerate(get_row(5), start = 1):
    print(i,':', r)

1 : [0]
2 : [0, 1]
3 : [0, 1, 2]
4 : [0, 1, 2, 3]
5 : [0, 1, 2, 3, 4]
