In [1]:
import tensorflow as tf

In [2]:
tf.GraphKeys.UPDATE_OPS

'update_ops'

In [3]:
type(tf.GraphKeys.UPDATE_OPS)

str

In [5]:
tf.get_collection('update_ops')

[]

In [5]:
import helper
from glob import glob
import os

In [7]:
data_dir = './data'

In [8]:
mnist_dataset = helper.Dataset('mnist', glob(os.path.join(data_dir, 'mnist/*.jpg')))

In [9]:
aa = mnist_dataset.get_batches

In [10]:
bb = mnist_dataset.shape

In [11]:
aa

<bound method Dataset.get_batches of <helper.Dataset object at 0x000002026991FC50>>

In [14]:
l1 = list()
for i in aa(128):
    l1.append(len(i))

In [15]:
l1

[128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128,
 128

In [16]:
len(l1)

468

In [17]:
468 * 128

59904

In [18]:
import numpy as np

In [24]:
a1 = np.random.randint(5, size =[3,3])
a1

array([[3, 2, 0],
       [3, 4, 4],
       [0, 0, 4]])

In [25]:
a2= np.random.randint(5, size =[1,3])
a2

array([[4, 0, 0]])

In [26]:
a1 + a2

array([[7, 2, 0],
       [7, 4, 4],
       [4, 0, 4]])

In [28]:
a3= np.random.randint(5, size =[3])
a3

array([1, 4, 1])

In [29]:
a1 + a3

array([[4, 6, 1],
       [4, 8, 5],
       [1, 4, 5]])

In [30]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [31]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [32]:
c.shape

(12288, 45)

In [54]:
# a.shape = (3,4)
# b.shape = (4,1)
a = np.random.randint(5, size=(3, 4), dtype= np.int0)
b = np.random.randint(5, size=(4, 1), dtype= np.int0)



In [61]:
a

array([[1, 3, 2, 3],
       [2, 4, 1, 4],
       [3, 1, 2, 0]], dtype=int64)

In [62]:
b

array([[4],
       [2],
       [1],
       [1]], dtype=int64)

In [70]:
c = np.zeros(shape= [3, 4])

In [72]:
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
        #print(c[i][j])
        #print(type(c))
        #print(c.shape)

In [73]:
c

array([[ 5.,  5.,  3.,  4.],
       [ 6.,  6.,  2.,  5.],
       [ 7.,  3.,  3.,  1.]])

In [74]:
c.shape

(3, 4)

In [75]:
 a + b.T

array([[5, 5, 3, 4],
       [6, 6, 2, 5],
       [7, 3, 3, 1]], dtype=int64)

In [76]:
np.product(c.shape)

12

In [77]:
a1 = np.ones(shape = [3,3])

In [78]:
a1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [79]:
np.sum(a1, axis=0, keepdims=True)

array([[ 3.,  3.,  3.]])

In [80]:
np.sum(a1, axis=0, keepdims=False)

array([ 3.,  3.,  3.])

In [81]:
np.sum(a1, axis=1, keepdims=True)

array([[ 3.],
       [ 3.],
       [ 3.]])

In [82]:
np.sum(a1, axis=1, keepdims=False)

array([ 3.,  3.,  3.])