In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[23,6,7]])

In [4]:
x

array([[ 1,  2,  3],
       [23,  6,  7]])

In [5]:
x.size

6

In [6]:
np.floor(x.size)

6.0

In [7]:
np.int(np.floor(x.size))

6

In [12]:
x.reshape((3,2))  == x.reshape(3,2)

array([[ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [1]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/")

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [2]:
X_test = mnist.test.images

In [3]:
X_test.shape

(10000, 784)

In [4]:
[1]*5

[1, 1, 1, 1, 1]

In [14]:
import tensorflow as tf

In [15]:
tf.reset_default_graph()

In [17]:
n_hidden = 2
num_layers = 3        
lstm_cell = tf.contrib.rnn.BasicLSTMCell(n_hidden)
stacked_lstm_cell = tf.contrib.rnn.MultiRNNCell([lstm_cell] * num_layers)
writer = tf . summary . FileWriter ( './graphs' , sess . graph)
with tf . Session () as sess:
    writer = tf . summary . FileWriter ( './graphs' , sess . graph)
    #print(sess . run ( x))
# close the writer when you’re done using it
writer.close()

In [30]:
tf.reset_default_graph()

In [31]:
v1 = tf.Variable([[[1,2],[2,4]],
                             [[2,3],[3,7]],
                             [[9,0],[89,11]]])

In [32]:
v1.get_shape()

TensorShape([Dimension(3), Dimension(2), Dimension(2)])

In [33]:
v1c = tf.concat(v1, axis= 1)

In [34]:
v1c.get_shape()

TensorShape([Dimension(3), Dimension(2), Dimension(2)])

In [35]:
v1c

<tf.Tensor 'concat:0' shape=(3, 2, 2) dtype=int32>

In [36]:
v1c == v1

False

In [37]:
v2 = v1*2

In [38]:
v2

<tf.Tensor 'mul:0' shape=(3, 2, 2) dtype=int32>

In [40]:
v2c = tf.concat((v1, v2), axis= 1)

In [41]:
v2c

<tf.Tensor 'concat_1:0' shape=(3, 4, 2) dtype=int32>

In [46]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run([v1,v2,v1c,v2c]))

[array([[[ 1,  2],
        [ 2,  4]],

       [[ 2,  3],
        [ 3,  7]],

       [[ 9,  0],
        [89, 11]]]), array([[[  2,   4],
        [  4,   8]],

       [[  4,   6],
        [  6,  14]],

       [[ 18,   0],
        [178,  22]]]), array([[[ 1,  2],
        [ 2,  4]],

       [[ 2,  3],
        [ 3,  7]],

       [[ 9,  0],
        [89, 11]]]), array([[[  1,   2],
        [  2,   4],
        [  2,   4],
        [  4,   8]],

       [[  2,   3],
        [  3,   7],
        [  4,   6],
        [  6,  14]],

       [[  9,   0],
        [ 89,  11],
        [ 18,   0],
        [178,  22]]])]


In [59]:
import numpy as np

In [73]:
matrix1 = np.array([[[1],[2]],
                             [[2],[3]],
                             [[9],[7]]])
matrix2 = 0.5*matrix1
matrix.shape

(3, 2, 2)

In [74]:
matrix1

array([[[1],
        [2]],

       [[2],
        [3]],

       [[9],
        [7]]])

In [75]:
matrix2

array([[[ 0.5],
        [ 1. ]],

       [[ 1. ],
        [ 1.5]],

       [[ 4.5],
        [ 3.5]]])

In [76]:
v1 = tf.Variable(matrix1, dtype= tf.float32)
v2 = tf.Variable(matrix2, dtype= tf.float32)

In [77]:
v1.get_shape()

TensorShape([Dimension(3), Dimension(2), Dimension(1)])

In [78]:
v2.get_shape()

TensorShape([Dimension(3), Dimension(2), Dimension(1)])

In [79]:
v1.get_shape().as_list()

[3, 2, 1]

In [80]:
vc0 = tf.concat([v1, v2], axis= 0)
vc1 = tf.concat([v1, v2], axis= 1)
vc2 = tf.concat([v1, v2], axis= 2)

In [81]:
vc0.shape, vc1.shape, vc2.shape

(TensorShape([Dimension(6), Dimension(2), Dimension(1)]),
 TensorShape([Dimension(3), Dimension(4), Dimension(1)]),
 TensorShape([Dimension(3), Dimension(2), Dimension(2)]))

In [85]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('vc0:')
    print(sess.run(vc0))
    print('\n')
    print('vc1:')
    print(sess.run(vc1))
    print('\n')
    print('vc2:')
    print(sess.run(vc2))

vc0:
[[[ 1. ]
  [ 2. ]]

 [[ 2. ]
  [ 3. ]]

 [[ 9. ]
  [ 7. ]]

 [[ 0.5]
  [ 1. ]]

 [[ 1. ]
  [ 1.5]]

 [[ 4.5]
  [ 3.5]]]


vc1:
[[[ 1. ]
  [ 2. ]
  [ 0.5]
  [ 1. ]]

 [[ 2. ]
  [ 3. ]
  [ 1. ]
  [ 1.5]]

 [[ 9. ]
  [ 7. ]
  [ 4.5]
  [ 3.5]]]


vc2:
[[[ 1.   0.5]
  [ 2.   1. ]]

 [[ 2.   1. ]
  [ 3.   1.5]]

 [[ 9.   4.5]
  [ 7.   3.5]]]


In [1]:
import tensorflow as tf

In [8]:
tf.reset_default_graph()
W = tf.Variable (10 , name= 'W')
assign_op = tf.assign(W, 100, name= 'assignX')
tf.summary.FileWriter('.', tf.get_default_graph())
with tf.Session () as sess:
    print(sess.run ( assign_op))
    #print W . eval () # >> 100

100


In [18]:
tf.reset_default_graph()
W = tf.Variable (10 , name= 'W')
assign_op = tf.assign_add(W, 100, name= 'assignX')
b = tf.Variable(20, name = 'bias')
out = tf.add(b, assign_op, name='output')
tf.summary.FileWriter('.', tf.get_default_graph())
with tf.Session () as sess:
    sess.run(tf.global_variables_initializer())
    what = sess.run(out)
    print(type(what))
    print(what)
    print(sess.run(out))
    print(sess.run(W))
    print(sess.run(W))
    #print W . eval () # >> 100

<class 'numpy.int32'>
130
230
210
210


In [12]:
type(b)

tensorflow.python.ops.variables.Variable

In [19]:
import numpy as np

In [21]:
p = np.array([  1.79670251e-03  , 8.48622341e-03  , 1.35987252e-03  , 2.20882706e-04
   ,4.13246271e-05   ,3.67764151e-05   ,6.17338010e-05   ,1.96004738e-04
   ,3.06342699e-05   ,1.35946219e-04   ,5.39845169e-05   ,3.62909795e-03
   ,6.72275375e-04   ,1.73283659e-03   ,2.71370700e-05   ,7.98285400e-05
   ,1.34425572e-04   ,1.19585042e-04   ,8.53222373e-05   ,6.26871915e-05
   ,1.02372680e-04   ,5.93961668e-05   ,1.08500048e-04   ,7.99504487e-05
   ,8.37917396e-05   ,2.79472326e-04   ,8.61068605e-04   ,1.04662147e-03
   ,2.90205189e-05   ,2.92611745e-04   ,2.16551591e-04   ,1.45310332e-04
   ,1.37882831e-04   ,1.47966333e-04   ,2.23203766e-04   ,3.83134990e-04
   ,1.59632211e-04   ,2.72602920e-04   ,5.07905243e-05   ,1.49904445e-04
   ,1.08252927e-04   ,5.41987829e-04   ,6.96272298e-04   ,1.52160515e-04
   ,3.74216499e-04   ,4.57430651e-05   ,4.32622473e-04   ,3.68362787e-04
   ,9.64334526e-04   ,7.71633495e-05   ,1.90186853e-04   ,1.98742040e-04
   ,8.22622533e-05   ,1.31116409e-04   ,5.31580081e-05   ,2.92567944e-04
   ,3.27887319e-05   ,4.82854759e-03   ,2.60753860e-03   ,2.99070291e-02
   ,7.63293132e-02   ,4.63220924e-02   ,4.48252587e-03   ,4.97466000e-03
   ,6.87842898e-04   ,1.02311019e-02   ,8.13345832e-04   ,1.48103843e-02
   ,1.28051788e-01   ,8.13773796e-02   ,5.86575679e-02   ,1.02015845e-02
   ,9.78331198e-04   ,1.20602874e-03   ,1.78933576e-01   ,2.45337915e-02
   ,2.59180695e-01   ,2.49908911e-03   ,1.37627441e-02   ,3.19025782e-03
   ,1.37731491e-03  , 9.77514032e-03   ,1.74523611e-03])

In [22]:
p.shape

(83,)

In [23]:
 p[np.argsort(p)]

array([  2.71370700e-05,   2.90205189e-05,   3.06342699e-05,
         3.27887319e-05,   3.67764151e-05,   4.13246271e-05,
         4.57430651e-05,   5.07905243e-05,   5.31580081e-05,
         5.39845169e-05,   5.93961668e-05,   6.17338010e-05,
         6.26871915e-05,   7.71633495e-05,   7.98285400e-05,
         7.99504487e-05,   8.22622533e-05,   8.37917396e-05,
         8.53222373e-05,   1.02372680e-04,   1.08252927e-04,
         1.08500048e-04,   1.19585042e-04,   1.31116409e-04,
         1.34425572e-04,   1.35946219e-04,   1.37882831e-04,
         1.45310332e-04,   1.47966333e-04,   1.49904445e-04,
         1.52160515e-04,   1.59632211e-04,   1.90186853e-04,
         1.96004738e-04,   1.98742040e-04,   2.16551591e-04,
         2.20882706e-04,   2.23203766e-04,   2.72602920e-04,
         2.79472326e-04,   2.92567944e-04,   2.92611745e-04,
         3.68362787e-04,   3.74216499e-04,   3.83134990e-04,
         4.32622473e-04,   5.41987829e-04,   6.72275375e-04,
         6.87842898e-04,

In [24]:
top_n=5

In [25]:
p[np.argsort(p)[:-top_n]] = 0

In [26]:
p

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.07632931,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.12805179,  0.08

In [33]:
x = np.array([[11, 21], [8, 33], [13, 32]])
x

array([[11, 21],
       [ 8, 33],
       [13, 32]])

In [34]:
np.argsort(x, axis=0)

array([[1, 0],
       [0, 2],
       [2, 1]], dtype=int64)

In [35]:
x[np.argsort(x, axis=0)]

array([[[ 8, 33],
        [11, 21]],

       [[11, 21],
        [13, 32]],

       [[13, 32],
        [ 8, 33]]])

In [36]:
x[0,0]

11

In [37]:
x[0]

array([11, 21])

In [38]:
np.random.choice(3, 3)

array([0, 2, 1])

In [40]:
np.random.choice(3, 3)

array([1, 2, 0])

In [42]:
np.random.choice(3, 1)

array([1])

In [43]:
np.random.choice(3, 1)[0]

2